package com.lijubjohn;

import org.hsqldb.Server;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by liju on 2/23/17.
 *
 * Standalone HSQL DB server
 */
public class DBServer {
    private Server hsqlDbServer;
    private Connection connection;
    private static final String DB_URL = "jdbc:hsqldb:hsql://localhost/EmployeeDB";
    private static final String DRIVER_CLASS = "org.hsqldb.jdbc.JDBCDriver";
    private boolean initialized = false;
    private final boolean autoCommit = false;
    private static final Logger log = LoggerFactory.getLogger(RestApp.class);

    public void startDBServer(){
        if (hsqlDbServer==null){
            hsqlDbServer = new Server();
            hsqlDbServer.setDatabasePath(0,"/tmp/hsqldb/EmployeeDB");
            hsqlDbServer.setDatabaseName(0, "EmployeeDB");
            hsqlDbServer.start();
            log.info("db server - started");
        }
    }

    public void shutDownDBServer() throws SQLException {
        log.info("shutting down db server");
        if (connection!=null){
            connection.close();
            log.info("db server - connection closed");
        }
        if (hsqlDbServer!=null){
            hsqlDbServer.shutdown();
            log.info("db server - shutdown successful");
        }
    }

    private void createHSQLDBConnection() throws SQLException, ClassNotFoundException {
        Class.forName(DRIVER_CLASS);
        connection = DriverManager.getConnection(DB_URL);
        connection.setAutoCommit(autoCommit);
        log.info("db server - connection created");
    }

    public void initializeDB() throws SQLException, ClassNotFoundException {
        try {
            if (!initialized){
                startDBServer();
                createHSQLDBConnection();
                dropTables();
                createTables();
                this.initialized = true;
            }
        } catch (Exception e) {
            shutDownDBServer();
            throw e;
        }
    }

    private void dropTables() throws SQLException {
        String sql = "DROP TABLE IF EXISTS EMPLOYEE";
        Statement st = null;
        try {
            st = connection.createStatement();
            st.executeUpdate(sql);
            connection.commit();
        }finally {
            if (st!=null)
                st.close();
        }
    }

    private void createTables() throws SQLException {
        String createEmployee =
                "CREATE TABLE " +
                        "EMPLOYEE(" +
                        "id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,"+
                        "first_name VARCHAR(30)," +
                        "last_name VARCHAR(30)," +
                        "dept VARCHAR(30))";


        Statement st = connection.createStatement();
        try {
            st.executeUpdate(createEmployee);
            connection.commit();
        } finally {
            st.close();
        }
    }

    public Connection getConnection() {
        return connection;
    }
}
